-- =============================================================================
-- Migracja 004 -- dostosowuje tresc dwoch przykladowych stron do nowej
-- konwencji "editable": pola przeznaczone do edycji z panelu /admin sa teraz
-- zapisane jako { "value": ..., "editable": true|false } zamiast zwyklego
-- stringa. Zobacz src/lib/editable.ts i backend/src/Support/Editable.php.
--
-- NIE tworzy ani nie usuwa zadnej tabeli -- tylko UPDATE istniejacych
-- wierszy o slug "/" i "/o-nas". Bez tej migracji panel /admin nie ma na
-- czym pokazac zadnej kontrolki do edycji (stare, "gole" pola tekstowe sa
-- dla niego niewidoczne -- to zamierzone, patrz EditableMerge.php).
--
-- Uruchom recznie, np.: mysql -u UZYTKOWNIK -p NAZWA_BAZY < db/004_wrap_editable_fields.sql
-- =============================================================================

UPDATE pages SET content = '{"slug":"/","parent":null,"template":"home","title":{"value":"Strona główna","editable":true},"updatedAt":"2026-08-31","status":"published","nav":{"label":"Strona główna","order":1},"seo":{"title":{"value":"KGD Group — strona główna","editable":true},"description":{"value":"Przykładowa strona główna zbudowana z pliku JSON w src/data/pages/home.json.","editable":true},"keywords":["kgd group","strona firmowa","next.js"],"canonical":null,"robots":{"index":true,"follow":true},"author":"KGD Group","ogTitle":null,"ogDescription":null,"ogImage":null,"ogType":"website","ogUrl":null,"ogSiteName":"KGD Group","ogLocale":"pl_PL","twitterCard":"summary_large_image","twitterTitle":null,"twitterDescription":null,"twitterImage":null,"language":"pl","structuredData":[{"type":"WebPage"}]},"sections":[{"id":"hero-home","component":"Hero","fields":{"eyebrow":{"value":"KGD Group","editable":true},"heading":{"value":"Tytuł strony głównej","editable":true},"lead":{"value":"To jest przykładowa treść wygenerowana z pliku src/data/pages/home.json. Podmień pola w JSON-ie albo w panelu /admin, żeby zmienić stronę.","editable":true},"primaryCta":{"label":"O nas","href":"/o-nas"}}},{"id":"o-firmie","component":"RichText","fields":{"heading":{"value":"O firmie","editable":true},"blocks":[{"type":"paragraph","text":"Ta sekcja pochodzi z komponentu RichText i pola \\"blocks\\" w JSON-ie. Każdy blok ma typ (paragraph, heading, list) i jest renderowany semantycznie."},{"type":"list","style":"bullet","items":["Nowa podstrona = nowy plik JSON w src/data/pages/","Nowy typ sekcji = nowy komponent zarejestrowany w src/lib/sections.tsx"]}]}}],"related":{"mode":"auto"}}' WHERE slug = '/';

UPDATE pages SET content = '{"slug":"/o-nas","parent":"/","template":"about","title":{"value":"O nas","editable":true},"updatedAt":"2026-08-31","status":"published","nav":{"label":"O nas","order":2,"summary":"Kim jest KGD Group i jak dodawać kolejne podstrony."},"seo":{"title":{"value":"O nas — KGD Group","editable":true},"description":{"value":"Przykładowa podstrona pokazująca, że wystarczy dodać plik JSON w src/data/pages, żeby powstał nowy adres.","editable":true},"keywords":["o nas","kgd group"],"canonical":null,"robots":{"index":true,"follow":true},"author":"KGD Group","ogTitle":null,"ogDescription":null,"ogImage":null,"ogType":"website","ogUrl":null,"ogSiteName":"KGD Group","ogLocale":"pl_PL","twitterCard":"summary_large_image","twitterTitle":null,"twitterDescription":null,"twitterImage":null,"language":"pl","structuredData":[{"type":"BreadcrumbList","from":"parent"},{"type":"WebPage"},{"type":"FAQPage","from":"section:faq-o-nas"}]},"sections":[{"id":"hero-o-nas","component":"Hero","fields":{"eyebrow":{"value":"O nas","editable":true},"heading":{"value":"Ta strona to plik src/data/pages/o-nas.json","editable":true},"lead":{"value":"Ścieżka pliku odpowiada adresowi: o-nas.json → /o-nas. Zagnieżdżony katalog, np. o-nas/zespol.json, dałby /o-nas/zespol.","editable":true},"internalId":{"value":"hero-o-nas-001","editable":false}}},{"id":"tresc-o-nas","component":"RichText","fields":{"heading":{"value":"Jak dodać kolejną podstronę","editable":true},"blocks":[{"type":"paragraph","text":"Skopiuj ten plik pod nową nazwą, zmień pole \\"slug\\" i uzupełnij sekcje. Router (src/app/[...slug]/page.tsx) wykryje go automatycznie przy kolejnym buildzie — nic więcej nie trzeba zmieniać."},{"type":"list","style":"number","items":["Utwórz plik JSON w src/data/pages/","Ustaw unikalny \\"slug\\" i opcjonalnie \\"parent\\"","Dodaj sekcje z listy zarejestrowanej w src/lib/sections.tsx","Uruchom npm run build, żeby sprawdzić eksport statyczny"]}]}},{"id":"faq-o-nas","component":"FAQ","label":"FAQ (komponent jeszcze nie istnieje — sekcja nie wyrenderuje się wizualnie)","fields":{"heading":"Częste pytania","items":[{"question":"Czy sekcja musi mieć gotowy komponent, żeby zasilić SEO?","answer":"Nie. Dane strukturalne (JSON-LD) czytają pole \\"fields.items\\" bezpośrednio z tej sekcji, niezależnie od tego, czy komponent FAQ jest już zarejestrowany w src/lib/sections.tsx."},{"question":"Co się stanie, gdy komponent sekcji nie istnieje?","answer":"SectionRenderer zaloguje ostrzeżenie w konsoli builda i pominie tę sekcję wizualnie — reszta strony renderuje się normalnie."}]}}],"related":{"mode":"auto"}}' WHERE slug = '/o-nas';
